# Mapping simplifié ville -> code IATA pour les recherches
CITY_TO_IATA = {
    'paris': 'CDG',
    'lisbonne': 'LIS',
    'barcelone': 'BCN',
    'rome': 'FCO',
    'madrid': 'MAD',
    'londres': 'LGW',
    'berlin': 'BER',
    'amsterdam': 'AMS',
    'vienne': 'VIE',
    'prague': 'PRG',
    'budapest': 'BUD',
    'athènes': 'ATH',
    'istanbul': 'IST',
    'dublin': 'DUB',
    'edimbourg': 'EDI',
    'stockholm': 'ARN',
    'copenhague': 'CPH',
    'oslo': 'OSL',
    'helsinki': 'HEL',
    'bruxelles': 'BRU',
    'zurich': 'ZRH',
    'genève': 'GVA',
    'milan': 'MXP',
    'venise': 'VCE',
    'florence': 'FLR',
    'naples': 'NAP',
    'porto': 'OPO',
    'sevilla': 'SVQ',
    'valencia': 'VLC',
    'nice': 'NCE',
    'marseille': 'MRS',
    'lyon': 'LYS',
    'bordeaux': 'BOD',
    'toulouse': 'TLS',
    'strasbourg': 'SXB',
    'nantes': 'NTE',
    'rennes': 'RNS',
    'lille': 'LIL',
    'reims': 'RHE',
}

# Mapping IATA -> nom de ville pour les hôtels
IATA_TO_CITY = {
    'CDG': 'Paris', 'ORY': 'Paris', 'BCN': 'Barcelona', 'MAD': 'Madrid',
    'FCO': 'Rome', 'LIS': 'Lisbon', 'LGW': 'London', 'LTN': 'London',
    'STN': 'London', 'AMS': 'Amsterdam', 'BER': 'Berlin', 'MUC': 'Munich',
    'VIE': 'Vienna', 'PRG': 'Prague', 'BUD': 'Budapest', 'ATH': 'Athens',
    'DUB': 'Dublin', 'EDI': 'Edinburgh', 'ARN': 'Stockholm', 'CPH': 'Copenhagen',
    'OSL': 'Oslo', 'HEL': 'Helsinki', 'BRU': 'Brussels', 'ZRH': 'Zurich',
    'GVA': 'Geneva', 'MXP': 'Milan', 'VCE': 'Venice', 'FLR': 'Florence',
    'NAP': 'Naples', 'OPO': 'Porto', 'SVQ': 'Seville', 'VLC': 'Valencia',
    'NCE': 'Nice', 'MRS': 'Marseille', 'LYS': 'Lyon', 'BOD': 'Bordeaux',
    'TLS': 'Toulouse', 'NTE': 'Nantes',
}
